### PR TITLE
Add the new registry to the enforce-image-registries kyverno policy

### PR DESCRIPTION
**Pull request by Strigix**
### Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by Strigix** [comment]
Why is the verify step failing???

**Comment by fhielpos** [comment]
Oh because this repo relies on black magic, give me a sec

**Comment by Strigix** [comment]
Would you be able to share some of that black magic knowledge with me?

**Comment by fhielpos** [comment]
You need to first modify this file:
https://github.com/giantswarm/kyverno-policies-dx/blob/main/policies/dx/EnforceGSRegistries.yaml

Then run this:
```
make generate
```

And then it should work

**Comment by Strigix** [comment]
Now it should work, if this is merged I'll be releasing it. Everything now triggers this policy since the new registry wasn't in it yet.

**Review by fhielpos — APPROVED** [review]

**Pull request merged**
